import turtle

car = turtle.Turtle()

# Draw upper body
car.color('red')
car.fillcolor('red')
car.penup()
car.goto(0, 0)
car.pendown()
car.begin_fill()
car.forward(370)
car.left(90)
car.forward(55)
car.left(90)
car.forward(370)
car.left(90)
car.forward(55)
car.end_fill()

# Draw window and roof
car.penup()
car.goto(100, 55)
car.pendown()
car.setheading(45)
car.forward(70)
car.setheading(0)
car.forward(100)
car.setheading(-45)
car.forward(70)
car.setheading(90)
car.penup()
car.goto(200, 55)
car.pendown()
car.forward(49.50)

# Draw tyres
car.penup()
car.goto(100, -10)
car.pendown()
car.color('black')
car.fillcolor('black')
car.begin_fill()
car.circle(25)
car.end_fill()
car.penup()
car.goto(300, -10)
car.pendown()
car.color('black')
car.fillcolor('black')
car.begin_fill()
car.circle(25)
car.end_fill()
